# Configurations: recipe.yaml
recipe = "classification/v1"
target_col = "is_red"
primary_metric = "f1_score"
steps = {
    "ingest": "{{INGEST_CONFIG}}",
    "transform": "{{TRANSFORM_CONFIG}}",
    "train": "{{TRAIN_CONFIG}}",
    "evaluate": {
        "using": "classification_metrics",
        "thresholds": {
            "f1_score": "{{VALIDATION_THRESHOLDS.f1_score}}",
            "precision_score": "{{VALIDATION_THRESHOLDS.precision_score}}",
            "recall_score": "{{VALIDATION_THRESHOLDS.recall_score}}"
        }
    }
}
