name: "sklearn_wine_classification"  # Nome della recipe

steps:
  - name: ingest_data
    using: "python_function"
    function: "ingest_data"
    artifact_location: "{{}}"  # Non ci sono output da registrare

  - name: transform_data
    using: "python_function"
    function: "transform_data"
    artifact_location: "{{}}"  # Non ci sono output da registrare

  - name: split_data
    using: "split"  # Utilizziamo lo split predefinito di MLflow
    ratios: "{{SPLIT_RATIOS}}"

  - name: train_model
    using: "python_function"
    function: "train_model"
    artifact_location: "model"  # Registra il modello addestrato

  - name: evaluate_model
    using: "python_function"
    function: "evaluate_model"
    artifact_location: "{{}}"  # Non ci sono output da registrare
    params:
      model_reference: "{{ previous_step.output_artifacts.model }}"  # Passa il modello addestrato

  - name: log_metrics
    using: "python_function"
    function: __builtin__.print  # Utilizziamo la funzione print per visualizzare le metriche
    code: |
      import mlflow
      print("F1 Score:", mlflow.get_metric_value("f1_score"))
      print("Precision Score:", mlflow.get_metric_value("precision_score"))
      print("Recall Score:", mlflow.get_metric_value("recall_score"))

# Parametri di valutazione (riferenziati da evaluate_model)
evaluation:
  metrics: "{{EVALUATION_METRICS}}"

# Step di valutazione finale (visualizza le metriche con print)
final_step: "log_metrics"