recipe: "classification/v1"
target_col: "is_red"
positive_class: 1
primary_metric: "f1_score"
steps:
  ingest:
    using: csv
    location: {{INGEST_CONFIG.location}}
    loader_method: {{INGEST_CONFIG.loader_method}}
  split:
    split_ratios: {{SPLIT_RATIOS|default([0.75, 0.125, 0.125])}}
  transform:
    transform_params: {{TRANSFORM_PARAMS|default({'method': 'dropna'})}}
  train:
    estimator_params: {{ESTIMATOR_PARAMS|default({'n_estimators': 100})}}
  validate:
    thresholds:
      f1_score: {{VALIDATION_THRESHOLDS.f1_score|default(0.75)}}
      precision_score: {{VALIDATION_THRESHOLDS.precision_score|default(0.75)}}
      recall_score: {{VALIDATION_THRESHOLDS.recall_score|default(0.75)}}
    allow_non_validated_model: {{ALLOW_NON_VALIDATED_MODEL|default(false)}}
  ingest_scoring:
    using: csv
    location: {{INGEST_SCORING_CONFIG.location}}
    loader_method: {{INGEST_SCORING_CONFIG.loader_method}}
  predict:
    format: {{PREDICTION_CONFIG.format}}
    location: {{PREDICTION_CONFIG.location}}