SPLIT_RATIOS: [0.80, 0.10, 0.10]
TRANSFORM_PARAMS:
  dropna: true
EVALUATION_THRESHOLDS:
  f1_score: 0.8
  precision_score: 0.75
  recall_score: 0.7
ALLOW_NON_VALIDATED_MODEL: false
INGEST_SCORING_CONFIG:
  location: ["./data/winequality-white.csv", "./data/winequality-red.csv"]
  format: "csv"
PREDICTION_CONFIG:
  location: "./data/prediction_input.csv"
  format: "csv"