recipe: "classification/v1"
target_col: "is_red"
primary_metric: "f1_score"

steps:
  ingest: {{INGEST_CONFIG}}
  
  split:
    split_ratios: {{SPLIT_RATIOS}}
    
  transform: {{TRANSFORM_CONFIG}}
  
  train:
    using: custom
    estimator_method: custom_estimator
    
  evaluate:
    validation_criteria:
      - metric: "f1_score"
        threshold: {{VALIDATION_F1_THRESHOLD}}
      - metric: "precision_score"
        threshold: {{VALIDATION_PRECISION_THRESHOLD}}
      - metric: "recall_score"
        threshold: {{VALIDATION_RECALL_THRESHOLD}}
    allow_non_validated_model: {{ALLOW_NON_VALIDATED}}