
recipe: "classification/v1"
target_col: "is_red"
positive_class: 1
primary_metric: "f1_score"
steps:
  ingest: {{INGEST_CONFIG}}
  split:
    split_ratios: {{SPLIT_RATIOS|default([0.80, 0.10, 0.10])}}
  transform:
    using: custom_transformer_fn
  train:
    using: custom_estimator_fn

thresholds:
  f1_score: 0.75

allow_non_validated_model: false

INGEST_CONFIG:
  using: csv
  location: ["./data/winequality-white.csv", "./data/winequality-red.csv"]
  loader_method: ingest_data

custom_transformer_fn:
  module: transform

custom_estimator_fn:
  module: train

custom_evaluator_fn:
  module: evaluate

