experiment:
  name: "sklearn_classification_experiment"
  tracking_uri: "sqlite:///metadata/mlflow/mlruns.db"
  artifact_location: "/metadata/mlflow/mlartifacts"

model_registry:
  model_name: "wine_classifier"

INGEST_CONFIG:
  using: csv
  location: ["./data/winequality-white.csv", "./data/winequality-red.csv"]
  delimiter: ";"  # Aggiunto per gestire il delimitatore ';'
  loader_method: ingest_data

SPLIT_RATIOS: [0.80, 0.10, 0.10]

TRANSFORM_CONFIG:
  method: "custom_transform"

TRAIN_CONFIG:
  estimator: "RandomForestClassifier"
  estimator_params: {}

F1_THRESHOLD: 0.85
PRECISION_THRESHOLD: 0.80
RECALL_THRESHOLD: 0.75
ALLOW_NON_VALIDATED_MODEL: false