experiment:
  name: "sklearn_classification_experiment"
  tracking_uri: "sqlite:///metadata/mlflow/mlruns.db"
  artifact_location: "/metadata/mlflow/mlartifacts"

model_registry:
  model_name: "wine_classifier"

INGEST_CONFIG:
  location: ["./data/winequality-white.csv", "./data/winequality-red.csv"]
  loader_method: "ingest_data"

SPLIT_RATIOS: [0.80, 0.10, 0.10]

TRANSFORM_PARAMS:
  method: 'dropna'

ESTIMATOR_PARAMS:
  n_estimators: 100

VALIDATION_THRESHOLDS:
  f1_score: 0.75
  precision_score: 0.75
  recall_score: 0.75

ALLOW_NON_VALIDATED_MODEL: false

INGEST_SCORING_CONFIG:
  location: "./data/scoring_data.csv"
  loader_method: "ingest_scoring_data"

PREDICTION_CONFIG:
  format: "csv"
  location: "./data/predictions.csv"