recipe: "classification/v1"
target_col: "is_red"
primary_metric: "f1_score"
steps:
  ingest:
    using: {{INGEST_CONFIG}}
  split:
    split_ratios: {{SPLIT_RATIOS|default([0.75, 0.125, 0.125])}}
  transform:
    transform_params: {{TRANSFORM_PARAMS|default({})}}
  train:
    estimator_params: {{ESTIMATOR_PARAMS|default({})}}
  evaluate:
    validation_thresholds: {{VALIDATION_THRESHOLDS}}
    allow_non_validated_model: {{ALLOW_NON_VALIDATED_MODEL|default(false)}}
