# recipe.yaml
recipe: "classification/v1"
target_col: "is_red"
primary_metric: "f1_score"

steps:
  ingest: {{INGEST_CONFIG}}
  split:
    split_ratios: {{SPLIT_RATIOS}}
  transform: {{TRANSFORM_CONFIG}}
  train:
    using: custom
    estimator_fn: train.estimator_fn
    estimator_params: {{ESTIMATOR_PARAMS}}
  evaluate:
    validation_criteria:
      - metric: f1_score
        threshold: {{METRICS_THRESHOLD.f1_score}}
      - metric: precision_score
        threshold: {{METRICS_THRESHOLD.precision_score}}
      - metric: recall_score
        threshold: {{METRICS_THRESHOLD.recall_score}}
    allow_non_validated_model: {{ALLOW_NON_VALIDATED}}