experiment:
  name: "sklearn_classification_experiment"
  tracking_uri: "sqlite:///metadata/mlflow/mlruns.db"
  artifact_location: "/metadata/mlflow/mlartifacts"

INGEST_CONFIG:
  using: csv
  location: ["./data/winequality-white.csv", "./data/winequality-red.csv"]
  delimiter: ";"
  loader_method: "ingest_data"

SPLIT_CONFIG:
  split_ratios: [0.80, 0.10, 0.10]

TRANSFORM_CONFIG:
  transform_method: "transform_data"

TRAIN_CONFIG:
  estimator_params:
    n_estimators: 100
    random_state: 42

EVALUATE_CONFIG:
  metrics: ["f1_score", "precision_score", "recall_score"]

ALLOW_NON_VALIDATED_MODEL: false