recipe: "classification/v1"
target_col: "is_red"
primary_metric: "f1_score"
steps:
  ingest: {{INGEST_CONFIG}}
  split:
    split_ratios: {{SPLIT_RATIOS|default([0.80, 0.10, 0.10])}}
  transform:
    transform_params: {{TRANSFORM_PARAMS}}
  train:
    estimator_params: {{ESTIMATOR_PARAMS}}
  evaluate:
    thresholds: {{THRESHOLDS}}
    allow_non_validated_model: {{ALLOW_NON_VALIDATED_MODEL}}
  predict:
    prediction_config: {{PREDICTION_CONFIG}}
