experiment:
  name: "sklearn_classification_experiment"
  tracking_uri: "sqlite:///metadata/mlflow/mlruns.db" 
  artifact_location: "/metadata/mlflow/mlartifacts" 

model_registry:
  model_name: "wine_classifier" 

INGEST_CONFIG:
  file_paths: ["./data/winequality-white.csv", "./data/winequality-red.csv"] 

SPLIT_RATIOS: [0.80, 0.10, 0.10]