recipe: "classification/v1"
target_col: "is_red"
positive_class: 1
primary_metric: "f1_score"
steps:
  ingest: {{INGEST_CONFIG}}
  split:
    split_ratios: {{SPLIT_RATIOS}}
  transform:
    transform_params: {{TRANSFORM_PARAMS}}
  train:
    train_params: {{TRAIN_PARAMS}}
  evaluate:
    thresholds: {{VALIDATION_THRESHOLDS}}
    registration:
      allow_non_validated_model: {{ALLOW_NON_VALIDATED_MODEL}}
