# recipe.yaml
recipe: "classification/v1"
target_col: "is_red"
positive_class: 1
primary_metric: "f1_score"

steps:
  ingest: {{INGEST_CONFIG}}
  split: 
    split_ratios: {{SPLIT_RATIOS}}
  transform: {{TRANSFORM_CONFIG}}
  train:
    using: custom
    estimator_method: train_method
  evaluate:
    validation_criteria:
      threshold:
        f1_score: {{F1_THRESHOLD}}
        precision_score: {{PRECISION_THRESHOLD}}
        recall_score: {{RECALL_THRESHOLD}}
    allow_non_validated_model: false