recipe: "classification/v1"
target_col: "is_red"
positive_class: 1
primary_metric: "f1_score"
steps:
  ingest: {{INGEST_CONFIG}}
  split:
    split_ratios: {{SPLIT_RATIOS|default([0.75, 0.125, 0.125])}}
  transform:
    transformer_fn: {{TRANSFORM_PARAMS}}
  train:
    estimator_fn: {{TRAIN_PARAMS}}
  evaluate:
    threshold: {{EVALUATION_THRESHOLD}}
  register:
    allow_non_validated_model: {{ALLOW_NON_VALIDATED_MODEL}}
  ingest_scoring: {{INGEST_SCORING_CONFIG}}
  predict: {{PREDICT_CONFIG}}
