recipe: "wine_classifier/v1"
target_col: "is_red"
positive_class: 1
primary_metric: "f1_score"
validation_thresholds:
  f1_score: 0.85
  precision_score: 0.80
  recall_score: 0.80
model_registry:
  model_name: "wine_classifier"
  allow_non_validated_model: {{ALLOW_NON_VALIDATED_MODEL|default(false)}}
steps:
  ingest: {{INGEST_CONFIG}}
  split: {{SPLIT_CONFIG}}
  transform: {{TRANSFORM_CONFIG}}
  train: {{TRAIN_CONFIG}}
  evaluate: {{EVALUATE_CONFIG}}